version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data

  django:
    build: ./
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=forfeits.settings
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0

  celery_worker:
    build: ./
    container_name: celery_worker
    command: celery -A forfeits worker -B --loglevel=info
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    container_name: redis

volumes:
  db_data: null

